config/routes.rb
Ihn::Application.routes.draw do

  root :to => "home#index"

  resource :accounts do
    collection do
      post :login
      get :logout
      post :avatar
      get :name
    end
  end

  resources :users do
    
  end

  match "/:username" => "accounts#index", :as => :user_dashboard_page, :via => :get 
  match "/:username/profile" => "accounts#profile", :as => :profile_page, :via => [:get, :post]
  match "/:username/messages" => "accounts#messages", :as => :messages_page, :via => [:get, :post]
  match	"/:username/settings" => "accounts#settings", :as => :settings_page, :via => [:get, :post]

  match	"/:username/hostels" => "hostels#index", :via => :get, :as => :hostels_page
  match "/:username/hostels" => "hostels#create", :via => :post, :as => :create_hostel
  match "/:username/hostels/new" => "hostels#new", :via => :get, :as => :new_hostel
  match "/:username/hostels/:id" => "hostels#show", :via => :get, :as => :hostel_page
  match "/:username/hostels/:id" => "hostels#update", :via => :put, :as => :update_hostel
  match "/:username/hostels/:id" => "hostels#destroy", :via => :delete, :as => :delete_hostel
  match "/:username/hostels/:id/edit" => "hostels#edit", :via => :get, :as => :edit_hostel
  match "/:username/hostels/:id/avatar" => "hostels#avatar", :via => :post, :as => :avatar_hostel

  match "/:username/hostels/:hostel_id/rooms" => "rooms#index", :via => :get, :as => :rooms_page
  match "/:username/hostels/:hostel_id/rooms" => "rooms#create", :via => :post, :as => :create_room
  match "/:username/hostels/:hostel_id/rooms/new" => "rooms#new", :via => :get, :as => :new_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#show", :via => :get, :as => :room_page
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#update", :via => :put, :as => :update_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#destroy", :via => :delete, :as => :delete_room
  match "/:username/hostels/:hostel_id/rooms/:id/edit" => "rooms#edit", :via => :get, :as => :edit_room
  match "/:username/hostels/:hostel_id/rooms/:id/avatar" => "rooms#avatar", :via => :post, :as => :room_avatar  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'home'

  def index

  end

end

app/views/home/_dashboard.html.erb
<div class="content-left">
  <div class="row1">
    <h1 class="title">Welcome <span><%= "#{@user.first_name} #{@user.last_name}" %></span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>
    <p>It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was
      popularised in the 1960s with the release </p>
    <ul class="list1">
      <li>of Letraset sheets containing</li>
      <li>Lorem Ipsum passages,</li>
      <li>and more recently with desktop</li>
    </ul>
    <p>&nbsp;<br>
      <strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it.<br>
      <br>
    </p>
  </div>
  <div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
    <hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"/></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Great beginning, I am very pleased with what I have seen about this program so far. I look forward to learning more, and generating a good income. <br><a class="more-news-a">2 minutes ago</a></p>
      </div>
    </div>  
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">5 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">10 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">George Glumac</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">15 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">20 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">21 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>    
  </div>
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it to make a type specimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color">My Profile</span>      
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 306px;"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div>
	<div style="">Profile is 21% complete</div>
	<div class="progress progress-striped active">
	  <div class="bar" style="width: 21%;"></div>
	</div>		
	<div style="clear:both;"></div>        
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/home/_index.html.erb
<div class="content-left">
  <div class="row1">
    <h1 class="title">Welcome To <span>India Hostels Network</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>
    <p>It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was
      popularised in the 1960s with the release </p>
    <ul class="list1">
      <li>of Letraset sheets containing</li>
      <li>Lorem Ipsum passages,</li>
      <li>and more recently with desktop</li>
    </ul>
    <p>&nbsp;<br>
      <strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it.<br>
      <br>
    </p>
  </div>  
  <div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
    <hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"/></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Great beginning, I am very pleased with what I have seen about this program so far. I look forward to learning more, and generating a good income. <br><a class="more-news-a">2 minutes ago</a></p>
      </div>
    </div>  
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">5 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">6 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Rose Robinson</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">10 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">George Glumac</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">15 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Harold Paul-Emile</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">20 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
    <div class="news_section">
      <div class="main_news_image"><a href="#"><img src="/images/image_05.jpg" alt="image 3" width="60px" height="60px"></a></div>
      <div class="main_feed_content">
        <div class="news_title">Janice Nagao</div>
        <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team! <br><a class="more-news-a">21 minutes ago</a></p>
      </div>
    </div>      
    <div class="margin_bottom_10"></div><hr/>
</div>
</div>

<div class="content-right">
  <div class="mainmenu">
    <h2 class="sidebar1">Join India Hostels Network</h2>
    <div class="text_box">
      <div class="login-title">Customer login</div>
      <%= form_for "user_login", :url => login_accounts_path, :html => {:method => :post} do %>
      <div class="login_form_row">
        <label class="login_label">Username:</label><input type="text" name="form[username]" class="login_input">
      </div>      
      <div class="login_form_row">
        <label class="login_label">Password:</label><input type="password" name="form[password]" class="login_input">
      </div>                                     
      <input type="image" src="/images/login.gif" class="login button">
      <% end %>
    </div>
    <!--<div class="signup-note">Don't have an account yet! &nbsp;&nbsp;<a href="<%= new_accounts_path%>">Signup</a></div>-->
  </div>
  <div class="contact">
    <h2 class="sidebar2">News Feed</h2>
    <div class="content_right_section">            
      <div class="header_02">What customers are saying..</div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">George Glumac</div>
          <p>I have checked out at least a dozen real estate investing systems in the past 16 months and spent a ton of money looking for integrity... 
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Rose Robinson</div>
          <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team!
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_07.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Joe Riddell</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	        <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
    </div>    
  </div>
</div>

app/views/home/index.html.erb
<% unless @user.nil?  %>
<%= render :partial => "dashboard" %>
<% else %>
<%= render :partial => "index" %>
<% end %>