config/routes.rb
Ihn::Application.routes.draw do

  root :to => "home#index"

  resource :accounts do
    collection do
      post :login
      get :logout
      post :avatar
      get :name
    end
  end

  resources :users do
    
  end

  match "/:username" => "accounts#index", :as => :user_dashboard_page, :via => :get 
  match "/:username/profile" => "accounts#profile", :as => :profile_page, :via => [:get, :post]
  match "/:username/messages" => "accounts#messages", :as => :messages_page, :via => [:get, :post]
  match	"/:username/settings" => "accounts#settings", :as => :settings_page, :via => [:get, :post]

  match	"/:username/hostels" => "hostels#index", :via => :get, :as => :hostels_page
  match "/:username/hostels" => "hostels#create", :via => :post, :as => :create_hostel
  match "/:username/hostels/new" => "hostels#new", :via => :get, :as => :new_hostel
  match "/:username/hostels/:id" => "hostels#show", :via => :get, :as => :hostel_page
  match "/:username/hostels/:id" => "hostels#update", :via => :put, :as => :update_hostel
  match "/:username/hostels/:id" => "hostels#destroy", :via => :delete, :as => :delete_hostel
  match "/:username/hostels/:id/edit" => "hostels#edit", :via => :get, :as => :edit_hostel
  match "/:username/hostels/:id/avatar" => "hostels#avatar", :via => :post, :as => :avatar_hostel

  match "/:username/hostels/:hostel_id/rooms" => "rooms#index", :via => :get, :as => :rooms_page
  match "/:username/hostels/:hostel_id/rooms" => "rooms#create", :via => :post, :as => :create_room
  match "/:username/hostels/:hostel_id/rooms/new" => "rooms#new", :via => :get, :as => :new_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#show", :via => :get, :as => :room_page
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#update", :via => :put, :as => :update_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#destroy", :via => :delete, :as => :delete_room
  match "/:username/hostels/:hostel_id/rooms/:id/edit" => "rooms#edit", :via => :get, :as => :edit_room
  match "/:username/hostels/:hostel_id/rooms/:id/avatar" => "rooms#avatar", :via => :post, :as => :room_avatar  

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  layout 'room'
  before_filter :ensure_user_is_logged_in!, :except => :show
  before_filter :init_current_user
      
  # GET /:username/hostels/:hostel_id/rooms
  def index
     redirect_to(@user.hostels_page, :notice => "Access denied") unless @user.username == params[:username]
     @hostel = Hostel.find_by_short_name(params[:hostel_id])
     @rooms = @hostel.available_rooms.all
  end
    
  # GET /:username/hostels/:hostel_id/rooms/:id
  def show
     @hostel = Hostel.find_by_short_name(params[:hostel_id])
     @room = AvailableRoom.find_by_id(params[:id])
  end

  # GET /:username/hostels/:hostel_id/rooms/new
  def new
     @hostel = Hostel.find_by_short_name(params[:hostel_id])
  end

  # POST /:username/hostels/:hostel_id/rooms
  def create
     hostel = Hostel.find_by_short_name(params[:hostel_id])
     room = hostel.available_rooms.create(params[:form])
     redirect_to room_page_url(@user.username, hostel.short_name, room.id)
  end

  # GET /:username/hostels/:hostel_id/rooms/:id/edit
  def edit
     @hostel = Hostel.find_by_short_name(params[:hostel_id])
     @room = AvailableRoom.find_by_id(params[:id])
     redirect_to(@user.home_page, :notice => "Access denied") unless current_user_is_owner?
  end
  
  # PUT /:username/hostels/:hostel_id/rooms/:id
  def update
     room = AvailableRoom.find_by_id(params[:id])
     room.update_attributes(params[:form])
     redirect_to room_page_url(@user.username, params[:hostel_id], room.id)
  end

  # DELETE /:username/hostels/:hostel_id/rooms/:id
  def destroy
     room = AvailableRoom.find_by_id(params[:id])
     redirect_to(@user.home_page, :notice => "Access denied") unless current_user_is_owner?
     room.destroy
     redirect_to @user.hostels_page, :notice => "Your hostel was successfully deleted"
  end

  def avatar
     room = AvailableRoom.find_by_id(params[:id])
     room.room_images.first.destroy unless room.room_images.empty?
     room_image = RoomImage.create(params[:room_image])
     room_image.available_room_id = room.id
     room_image.save!
     redirect_to room_page_url(@user.username, params[:hostel_id], room.id)
  end

  private

  def current_user_is_owner?
     (@user.username == params[:username] and @user.id == @hostel.user_id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<% @tab = []; @tab[2] = 'active'%>
<div class="content-left">
  <div class="row1">
    <h1 class="title"><span><%= @hostel.name %></span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <!--<p>&nbsp;</p>-->
    <%= form_for "user_form", :url => update_room_path(@user.username, @hostel.short_name, @room.id), :html => {:method => :put} do %>
      <div class="profile-form">
	<div class="form-row">
          <label for="name">Total Capacity: <span style="color:red"> *</span></label>
	  <input name="form[capacity]" size="30" type="text" value="<%= @room.capacity %>">
	</div>

        <div class="form-row">
          <label for="address">Available Vacancies: <span style="color:red"> *</span></label>
          <input name="form[vacancies]" size="30" type="text" value="<%= @room.vacancies %>">
	</div>

        <div class="form-row">
          <label for="phone1">Room Rent: <span style="color:red"> *</span></label>
          <input name="form[rent]" size="30" type="text" value="<%= @room.rent %>">
	</div>

        <div class="form-row">
          <label for="phone2">Describe the room: <span style="color:red"> *</span></label>
          <input name="form[description]" size="30" type="text" value="<%= @room.description %>">
	</div>

        <div style="clear:both;"></div>
        <input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>
    <% end %>
  </div>
  <!--<div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
  </div>-->
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= @hostel.name %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @hostel.hostel_images.first.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/rooms/index.html.erb
<% @tab = []; @tab[2] = 'active' %>
<div class="content-left">
  <% @rooms.each do |r| %>
  <div class="row2">
    <h2 class="subtitle"><%= @hostel.name %> <span></span></h2>
    <p>
      <strong>Room Type:</strong> <%= r.type %><br>
      <strong>Contacts:</strong> <%= @hostel.contact_one %>, <%= @hostel.contact_two %>, <%= @hostel.contact_three %><br>
      <strong>Address:</strong> <%= @hostel.address %><br>
    </p>
    <p>
      <strong>New Messages:</strong> 16<br>
      <strong>Total Messages :</strong> 100
    </p>
    <p align="right"><a href="<%= edit_hostel_path(@user.username, @hostel.id)%>" class="more">Edit</a></p>
  </div>
  <% end %>
  <div class="row2">
    <h2 class="subtitle">Add new room <span></span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry.</p>
    <p align="right"><a href="<%= new_room_path(@user.username, @hostel.short_name)%>" class="more">Add</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= @hostel.name %></span>      
      <span style="float:right;font-size:14px;"><a href="<%= hostel_page_url(@user.username, @hostel.id) %>" class="more-news-a">View</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @hostel.hostel_images.empty? ? "/images/image_01.jpg" : @hostel.hostel_images.first.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div> /images/image_03.jpg -->
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>

<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/rooms/new.html.erb
<% @tab = []; @tab[2] = 'active'%>
<div class="content-left">
  <div class="row1">
    <h1 class="title"><span><%= @hostel.name %></span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <!--<p>&nbsp;</p>-->
    <%= form_for "room_form", :url => create_room_path(@user.username, @hostel.short_name), :html => {:method => :post} do %>
      <div class="profile-form">
        <div class="form-row">
          <label for="name">Total Capacity: <span style="color:red"> *</span></label>
          <input name="form[capacity]" size="30" type="text">
        </div>

        <div class="form-row">
          <label for="address">Available Vacancies: <span style="color:red"> *</span></label>
          <input name="form[vacancies]" size="30" type="text">
	</div>

        <div class="form-row">
          <label for="phone1">Room Rent: <span style="color:red"> *</span></label>
          <input name="form[rent]" size="30" type="text">
        </div>

	<div class="form-row">
          <label for="phone2">Describe the room: <span style="color:red"> *</span></label>
          <input name="form[description]" size="30" type="text">
        </div>

        <div style="clear:both;"></div>
        <input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>
    <% end %>
  </div>
  <!--<div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
  </div>-->
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= "#{@user.first_name} #{@user.last_name}" %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @user.profile_image.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div>-->
	<div style="">Your profile is 21% complete</div>
	<div class="progress progress-striped active">
	  <div class="bar" style="width: 21%;"></div>
	</div>		
	<div style="clear:both;"></div>        
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/rooms/show.html.erb
<% @tab = []; @tab[2] = 'active' %>
<div class="content-left">

  <div class="row2">
    <h2 class="subtitle"><%= @hostel.name %> <span></span></h2>
    <p>
      <strong>Total Capacity:</strong> <%= @room.capacity %><br>
      <strong>Available Vacancies:</strong> <%= @room.vacancies %><br>
      <strong>Room rent:</strong> Rs <%= @room.rent %><br>
    </p>
    <p>
      <strong>About room:</strong> <%= @room.description %><br>
    </p>
    <p align="right"><a href="<%= edit_room_path(@user.username, @hostel.short_name, @room.id)%>" class="more">Edit</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= @hostel.name %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @room.room_images.empty? ? "/images/image_01.jpg" : @room.room_images.first.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div> /images/image_03.jpg -->
        <%= form_for "room_image", :url => room_avatar_path(@user.username, @hostel.short_name, @room.id), :html => {:method => :post, :multipart => true} do |f| %>
	   <input type="hidden" name="room_image[available_room_id]" value="<%= @room.id %>" />
	   <%= f.file_field :avatar %>
	   <input type="submit" value="Upload" />
	<% end %>
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>

<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>