config/routes.rb
Ihn::Application.routes.draw do

  root :to => "home#index"

  resource :accounts do
    collection do
      post :login
      get :logout
      post :avatar
      get :name
    end
  end

  resources :users do
    
  end

  match "/:username" => "accounts#index", :as => :user_dashboard_page, :via => :get 
  match "/:username/profile" => "accounts#profile", :as => :profile_page, :via => [:get, :post]
  match "/:username/messages" => "accounts#messages", :as => :messages_page, :via => [:get, :post]
  match	"/:username/settings" => "accounts#settings", :as => :settings_page, :via => [:get, :post]

  match	"/:username/hostels" => "hostels#index", :via => :get, :as => :hostels_page
  match "/:username/hostels" => "hostels#create", :via => :post, :as => :create_hostel
  match "/:username/hostels/new" => "hostels#new", :via => :get, :as => :new_hostel
  match "/:username/hostels/:id" => "hostels#show", :via => :get, :as => :hostel_page
  match "/:username/hostels/:id" => "hostels#update", :via => :put, :as => :update_hostel
  match "/:username/hostels/:id" => "hostels#destroy", :via => :delete, :as => :delete_hostel
  match "/:username/hostels/:id/edit" => "hostels#edit", :via => :get, :as => :edit_hostel
  match "/:username/hostels/:id/avatar" => "hostels#avatar", :via => :post, :as => :avatar_hostel

  match "/:username/hostels/:hostel_id/rooms" => "rooms#index", :via => :get, :as => :rooms_page
  match "/:username/hostels/:hostel_id/rooms" => "rooms#create", :via => :post, :as => :create_room
  match "/:username/hostels/:hostel_id/rooms/new" => "rooms#new", :via => :get, :as => :new_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#show", :via => :get, :as => :room_page
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#update", :via => :put, :as => :update_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#destroy", :via => :delete, :as => :delete_room
  match "/:username/hostels/:hostel_id/rooms/:id/edit" => "rooms#edit", :via => :get, :as => :edit_room
  match "/:username/hostels/:hostel_id/rooms/:id/avatar" => "rooms#avatar", :via => :post, :as => :room_avatar  

end

app/models/hostel.rb
class Hostel < ActiveRecord::Base
      belongs_to :user
      belongs_to :region
      has_many :hostel_images
      has_many :available_rooms
      has_and_belongs_to_many :hostel_types
end

app/models/hostel_type.rb
class HostelType < ActiveRecord::Base
      has_and_belongs_to_many :hostels
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  
  layout 'hostel'
  before_filter :ensure_user_is_logged_in!, :except => :show
  before_filter :init_current_user
 
  # GET /:username/hostels
  def index
     redirect_to(@user.hostels_page, :notice => "Access denied") unless @user.username == params[:username] 
     @hostels = @user.hostels.all
  end
    
  # GET /:username/hostels/:id  
  def show
     @hostel = Hostel.find_by_short_name(params[:id])
  end

  # GET /:username/hostels/new
  def new

  end

  # POST /:username/hostels
  def create
     form = params[:form].merge({:short_name => params[:form][:name].gsub(/(\s)+/, '').downcase})
     hostel = @user.hostels.create(form)
     redirect_to @user.hostel_page(hostel.short_name)
  end

  # GET /:username/hostels/:id/edit
  def edit
     @hostel = Hostel.find_by_short_name(params[:id])
     redirect_to(@user.home_page, :notice => "Access denied") unless current_user_is_owner?
  end

  # PUT /:username/hostels/:id
  def update
     form = params[:form].merge({:short_name => params[:form][:name].gsub(/(\s)+/, '').downcase})
     hostel = Hostel.find_by_short_name(params[:id])
     hostel.update_attributes(form)
     redirect_to @user.hostel_page(hostel.short_name)
  end

  # DELETE /:username/hostels/:id
  def destroy
     hostel = Hostel.find_by_short_name(params[:id])
     redirect_to(@user.home_page, :notice => "Access denied") unless current_user_is_owner?
     hostel.destroy
     redirect_to @user.hostels_page, :notice => "Your hostel was successfully deleted" 
  end

  def avatar
     hostel = Hostel.find_by_short_name(params[:id])
     unless hostel.hostel_images.empty?
        hostel.hostel_images.first.destroy
     end
     hostel_image = HostelImage.create(params[:hostel_image])
     hostel_image.hostel_id = hostel.id
     hostel_image.save!
     redirect_to hostel_page_url(@user.username, hostel.short_name)
  end

  private

  def current_user_is_owner?
     (@user.username == params[:username] and @user.id == @hostel.user_id)
  end

end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/views/hostels/edit.html.erb
<% @tab = []; @tab[2] = 'active'%>
<div class="content-left">
  <div class="row1">
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <!--<p>&nbsp;</p>-->
    <%= form_for "user_form", :url => update_hostel_path(@user.username, @hostel.short_name), :html => {:method => :put} do %>
      <div class="profile-form">
        <div class="form-row">
          <label for="name">Hostel Name: <span style="color:red"> *</span></label>
          <input name="form[name]" size="30" type="text" value="<%= @hostel.name %>">
        </div>

        <div class="form-row">
          <label for="address">Hostel Address: <span style="color:red"> *</span></label>
          <input name="form[address]" size="30" type="text" value="<%= @hostel.address %>">
	</div>

        <div class="form-row">
          <label for="phone1">Contact Number: <span style="color:red"> *</span></label>
          <input name="form[contact_one]" size="30" type="text" value="<%= @hostel.contact_one %>">
        </div>

	<div class="form-row">
          <label for="phone2">Contact Number 2: <span style="color:red"> *</span></label>
          <input name="form[contact_two]" size="30" type="text" value="<%= @hostel.contact_two %>">
        </div>

	<div class="form-row">
          <label for="phone3">Contact Number 3: <span style="color:red"> *</span></label>
          <input name="form[contact_three]" size="30" type="text" value="<%= @hostel.contact_three %>">
        </div>

	<div class="form-row">
          <label for="email">Email: <span style="color:red"> *</span></label>
          <input name="form[email]" size="30" type="text" value="<%= @hostel.email %>">
        </div>

        <div style="clear:both;"></div>
        <input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>
    <% end %>
  </div>
  <!--<div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
  </div>-->
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= @hostel.name %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%#= @hostel.hostel_images.first.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/hostels/index.html.erb
<% @tab = []; @tab[2] = 'active' %>
<div class="content-left">
  <% @hostels.each do |hostel| %>
  <div class="row2">
    <h2 class="subtitle"><%= hostel.name %> <span></span></h2>
    <p>
      <strong>Email:</strong> <%= hostel.email %><br>
      <strong>Contacts:</strong> <%= hostel.contact_one %>, <%= hostel.contact_two %>, <%= hostel.contact_three %><br>
      <strong>Address:</strong> <%= hostel.address %><br>
    </p>
    <p>
      <strong>New Messages:</strong> 16<br>
      <strong>Total Messages :</strong> 100
    </p>
    <p align="right">
      <a href="<%= edit_hostel_path(@user.username, hostel.short_name)%>" class="more">Edit</a>
      <a href="<%= rooms_page_path(@user.username, hostel.short_name)%>" class="more">Rooms</a>
    </p>
  </div>
  <% end %>
  <div class="row2">
    <h2 class="subtitle">Add new hostel <span></span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry.</p>
    <p align="right"><a href="<%= new_hostel_path(@user.username)%>" class="more">Add</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= "#{@user.first_name} #{@user.last_name}" %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @user.profile_image.nil? ? "/images/default-image.jpg" : @user.profile_image.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div> /images/image_03.jpg -->
	<div style="">Your profile is 21% complete</div>
	<div class="progress progress-striped active">
	  <div class="bar" style="width: 21%;"></div>
	</div>		
	<div style="clear:both;"></div>
        <%= form_for "profile_image_form", :url => avatar_accounts_path, :html => {:method => :post, :multipart => true} do |f| %>
	   <input type="hidden" name="profile_image_form[user_id]" value="<%= @user.id %>" />
	   <%= f.file_field :avatar %>
	   <input type="submit" value="Upload" />
	<% end %>
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>

<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/hostels/show.html.erb
<% @tab = []; @tab[2] = 'active' %>
<div class="content-left">

  <div class="row2">
    <h2 class="subtitle"><%= @hostel.name %> <span></span></h2>
    <p>
      <strong>Email:</strong> <%= @hostel.email %><br>
      <strong>Contacts:</strong> <%= @hostel.contact_one %>, <%= @hostel.contact_two %>, <%= @hostel.contact_three %><br>
      <strong>Address:</strong> <%= @hostel.address %><br>
    </p>
    <p>
      <strong>New Messages:</strong> 16<br>
      <strong>Total Messages :</strong> 100
    </p>
    <p align="right"><a href="<%= edit_hostel_path(@user.username, @hostel.short_name)%>" class="more">Edit</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= @hostel.name %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @hostel.hostel_images.empty? ? "/images/image_01.jpg" : @hostel.hostel_images.first.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div> /images/image_03.jpg -->
        <%= form_for "hostel_image", :url => avatar_hostel_path(@user.username, @hostel.short_name), :html => {:method => :post, :multipart => true} do |f| %>
	   <%= f.file_field :avatar %>
	   <input type="submit" value="Upload" />
	<% end %>
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>

<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>