config/routes.rb
Ihn::Application.routes.draw do

  root :to => "home#index"

  resource :accounts do
    collection do
      post :login
      get :logout
      post :avatar
      get :name
    end
  end

  resources :users do
    
  end

  match "/:username" => "accounts#index", :as => :user_dashboard_page, :via => :get 
  match "/:username/profile" => "accounts#profile", :as => :profile_page, :via => [:get, :post]
  match "/:username/messages" => "accounts#messages", :as => :messages_page, :via => [:get, :post]
  match	"/:username/settings" => "accounts#settings", :as => :settings_page, :via => [:get, :post]

  match	"/:username/hostels" => "hostels#index", :via => :get, :as => :hostels_page
  match "/:username/hostels" => "hostels#create", :via => :post, :as => :create_hostel
  match "/:username/hostels/new" => "hostels#new", :via => :get, :as => :new_hostel
  match "/:username/hostels/:id" => "hostels#show", :via => :get, :as => :hostel_page
  match "/:username/hostels/:id" => "hostels#update", :via => :put, :as => :update_hostel
  match "/:username/hostels/:id" => "hostels#destroy", :via => :delete, :as => :delete_hostel
  match "/:username/hostels/:id/edit" => "hostels#edit", :via => :get, :as => :edit_hostel
  match "/:username/hostels/:id/avatar" => "hostels#avatar", :via => :post, :as => :avatar_hostel

  match "/:username/hostels/:hostel_id/rooms" => "rooms#index", :via => :get, :as => :rooms_page
  match "/:username/hostels/:hostel_id/rooms" => "rooms#create", :via => :post, :as => :create_room
  match "/:username/hostels/:hostel_id/rooms/new" => "rooms#new", :via => :get, :as => :new_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#show", :via => :get, :as => :room_page
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#update", :via => :put, :as => :update_room
  match "/:username/hostels/:hostel_id/rooms/:id" => "rooms#destroy", :via => :delete, :as => :delete_room
  match "/:username/hostels/:hostel_id/rooms/:id/edit" => "rooms#edit", :via => :get, :as => :edit_room
  match "/:username/hostels/:hostel_id/rooms/:id/avatar" => "rooms#avatar", :via => :post, :as => :room_avatar  

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  layout 'account'

  #before_filter :ensure_user_is_logged_in!, :init_current_user, :except => [:login, :new, :create]
   before_filter :init_current_user, :except => [:login, :new, :create]
  def index

  end

  def show
    
  end

  def profile
     if request.post?
     	@user.update_attributes(params[:form])
     end 
  end

  def messages

  end

  def settings

  end

  def avatar
     unless @user.profile_image.nil?
     	@user.profile_image.destroy    
     end
     @profile_image = ProfileImage.create(params[:profile_image_form])
     @profile_image.user_id = @user.id
     @profile_image.save!
     redirect_to user_dashboard_page_url(@user.username)
  end

  def login
    user = User.find_by_username(params[:form][:username])
    
    if user
      session[:user_id] = user.id
      user.currently_logged_in_at = Time.now
      user.save!
      redirect_to "/#{user.username}"
    else
      redirect_to root_path
    end
  end

  def logout
    init_current_user
    @user.last_logged_in_on = @user.currently_logged_in_at
    @user.currently_logged_in_at = nil
    reset_session
    redirect_to root_path
  end

  def new
    render :layout => 'home'
  end

  def create
    user_type = UserType.find_by_permalink("nl")
    user = user_type.users.new(params[:form])    
    user.save!
    session[:user_id] = user.id
    redirect_to "/#{user.username}"
  end

  def destroy
      
  end

end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/destroy.html.erb
<h1>Accounts#destroy</h1>
<p>Find me in app/views/accounts/destroy.html.erb</p>

app/views/accounts/hostels.html.erb
<% @tab = []; @tab[2] = 'active'%>
<div class="content-left">
  <div class="row1">
    <h1 class="title"><span>My Hostels</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <!--<p>&nbsp;</p>-->
    <%= form_for "user_form", :url => hostels_page_path(@user.username), :html => {:method => :post} do %>
      <div class="profile-form">
        <div class="form-row">
          <label for="address">Hostel Name: <span style="color:red"> *</span></label>
          <input name="form[name]" size="30" type="text" value="<%#= @user.first_name %>">
        </div>

        <div class="form-row">
          <label for="sqft">Hostel Address: <span style="color:red"> *</span></label>
          <input name="form[name]" size="30" type="text" value="<%#= @user.last_name %>">
	</div>

        <div class="form-row">
          <label for="phone2">Contact Number: <span style="color:red"> *</span></label>
          <input name="form[contact_one]" size="30" type="text" value="<%#= @user.contact_one %>">
        </div>

	<div class="form-row">
          <label for="phone2">Contact Number 2: <span style="color:red"> *</span></label>
          <input name="form[contact_two]" size="30" type="text" value="<%#= @user.contact_two %>">
        </div>

	<div class="form-row">
          <label for="phone2">Contact Number 3: <span style="color:red"> *</span></label>
          <input name="form[contact_three]" size="30" type="text" value="<%#= @user.contact_two %>">
        </div>

	<div class="form-row">
          <label for="phone2">Email: <span style="color:red"> *</span></label>
          <input name="form[email]" size="30" type="text" value="<%#= @user.email %>">
        </div>

        <div style="clear:both;"></div>
        <input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>
    <% end %>
  </div>
  <!--<div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
  </div>-->
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= "#{@user.first_name} #{@user.last_name}" %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @user.profile_image.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div>-->
	<div style="">Your profile is 21% complete</div>
	<div class="progress progress-striped active">
	  <div class="bar" style="width: 21%;"></div>
	</div>		
	<div style="clear:both;"></div>        
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/accounts/login.html.erb
<h1>Accounts#login</h1>
<p>Find me in app/views/accounts/login.html.erb</p>

app/views/accounts/logout.html.erb
<h1>Accounts#logout</h1>
<p>Find me in app/views/accounts/logout.html.erb</p>

app/views/accounts/new.html.erb
<div class="content-left">  
  <div class="row1">    
    <h1 class="title">Welcome To <span>India Hostels Network</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <%= form_for "user_form", :url => accounts_path, :html => {:method => :post} do %>
      <div id="bluebox" class="nice" style="margin-left: 80px;margin-top: 63px;margin-bottom:16px;">
	<div class="corner"></div><div class="tag"></div>
	<div class="text-with-tag"><strong>Fill out the information below to submit your property to our network of investors and their buyers</strong></div>
	
	<div class="form-row">
	  <label for="address">First Name: <span style="color:red"> *</span></label>
	  <input name="form[first_name]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="sqft">Last Name: <span style="color:red"> *</span></label>
	  <input name="form[last_name]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="monthly">Username: <span style="color:red"> *</span></label>
	  <input name="form[username]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <label for="phone">Password: <span style="color:red"> *</span></label>
	  <input name="form[password]" size="30" type="password">
	</div>
	
	<div class="form-row">
	  <label for="phone2">Contact Number: <span style="color:red"> *</span></label>
	  <input name="form[contact_one]" size="30" type="text">
	</div>
	
	<div class="form-row">
	  <input type="checkbox" name="marketing_release"> <span style="padding-right: 10px;"><strong>By checking this box, I give you permission to submit my house to your buyers network to see how many offers I receive.  I understand I am Not obligated to sell my house under this program.</strong></span>
	</div>
	<div style="clear:both;"></div>
	<input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>            
    <% end %>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>
    <p>It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was
      popularised in the 1960s with the release </p>
    <ul class="list1">
      <li>of Letraset sheets containing</li>
      <li>Lorem Ipsum passages,</li>
      <li>and more recently with desktop</li>
    </ul>
    <p>&nbsp;<br>
      <strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it.<br>
      <br>
    </p>
  </div>
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the industry's standard
      dummy text ever since the 1500s, when an unknown printer took a galley
      of type and scrambled it to make a type specimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="mainmenu">
    <h2 class="sidebar1">Join India Hostels Network</h2>
    <div class="text_box">
      <div class="login-title">Customer login</div>
      <%= form_for "user_login", :url => login_accounts_path, :html => {:method => :post} do %>
      <div class="login_form_row">
        <label class="login_label">Username:</label><input type="text" name="form[username]" class="login_input">
      </div>      
      <div class="login_form_row">
        <label class="login_label">Password:</label><input type="password" name="form[password]" class="login_input">
      </div>                                     
      <input type="image" src="/images/login.gif" class="login button">
      <% end %>
    </div>
  </div>
  <div class="contact">
    <h2 class="sidebar2">News Feed</h2>
    <div class="content_right_section">            	
      <div class="header_02">What customers are saying..</div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_03.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">George Glumac</div>
          <p>I have checked out at least a dozen real estate investing systems in the past 16 months and spent a ton of money looking for integrity... 
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_04.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_01.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Rose Robinson</div>
          <p>Wow! I love this site, it seems so powerful. I'm looking forward to learning and earning w/this system. Tks Phill & Team!
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_06.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Harold Paul-Emile</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
      <div class="news_section">
        <div class="news_image"><a href="#"><img src="/images/image_07.jpg" alt="image 3" width="80px" height="80px"></a></div>
        <div class="news_content">
          <div class="news_title">Joe Riddell</div>
          <p>Looks like a solid program and network database for matching of buyers and sellers and very uniquely being able to work with other investors...
	    <br><a href="#" class="more-news-a">Details</a></p>
        </div>
      </div>      
      <div class="margin_bottom_20"></div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<% @tab = []; @tab[3] = 'active'%>
<div class="content-left">
  <div class="row1">
    <h1 class="title"><span>My Profile</span></h1>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the indusstandard dummy
      text ever since the 1500s, when an unknown printer took a galley of
      type and scrambleto make a type specimen book.</p>
    <p>&nbsp;</p>

    <%= form_for "user_form", :url => profile_page_path(@user.username), :html => {:method => :post} do %>
      <div class="profile-form">
        <div class="form-row">
          <label for="address">First Name: <span style="color:red"> *</span></label>
          <input name="form[first_name]" size="30" type="text" value="<%= @user.first_name %>">
        </div>

        <div class="form-row">
          <label for="sqft">Last Name: <span style="color:red"> *</span></label>
          <input name="form[last_name]" size="30" type="text" value="<%= @user.last_name %>">
	  </div>

	<div class="form-row">
          <label for="monthly">Username: <span style="color:red"> *</span></label>
          <input name="form[username]" size="30" type="text" value="<%= @user.username %>">
	</div>

        <div class="form-row">
          <label for="phone2">Contact Number: <span style="color:red"> *</span></label>
          <input name="form[contact_one]" size="30" type="text" value="<%= @user.contact_one %>">
        </div>

	<div class="form-row">
          <label for="phone2">Alternate Number: <span style="color:red"> *</span></label>
          <input name="form[contact_two]" size="30" type="text" value="<%= @user.contact_two %>">
        </div>

	<div class="form-row">
          <label for="phone2">Email: <span style="color:red"> *</span></label>
          <input name="form[email]" size="30" type="text" value="<%= @user.email %>">
        </div>

	<div class="form-row">
          <label for="phone2">Current Address: <span style="color:red"> *</span></label>
          <input name="form[address]" size="100" type="text" value="<%= @user.address %>">
        </div>

        <div style="clear:both;"></div>
        <input type="image" src="/images/btn-go.png" class="go" style="margin-top: 10px;">
      </div>
    <% end %>
  </div>
  <!--<div class="row1">
    <h1 class="title"><span style="color: #137DC0;">Find what's happening right now..</span></h1>
  </div>-->
  <div class="row2">
    <h2 class="subtitle">About <span>Us</span></h2>
    <p><strong>Lorem Ipsum is simply dummy text</strong> of the printing
      and typesetting industry. Lorem Ipsum has been the aaaa industry's
      standard dummy text ever since the 1500s, ass as dwhen an unknasdown
      printer took a galley of type and scrambled it to make a type
      speascimen book. <br>
      It has survived not only five centuries, but also the leap into
      electronic typesetting.and scrambled it to make a type speascimen book.</p>
    <p>&nbsp;</p>
    <p align="right"><a href="#" class="more">Read More</a></p>
  </div>
</div>
<div class="content-right">
  <div class="content_right_section">            	
    <div class="header_02">
      <span class="green-color"><%= "#{@user.first_name} #{@user.last_name}" %></span>      
      <span style="float:right;font-size:14px;"><a href="/accounts/logout" class="more-news-a">Logout</a></span>
    </div>
    <div class="news_section">
      <div class="news_image" style="width: 310px;"><a href="#"><img src="<%= @user.profile_image.nil? ? "/images/default-image.jpg" : @user.profile_image.avatar.url(:medium) %>" alt="image 3" width="310px" height="200px"></a></div>
      <div class="news_content" style="width:310px;">
        <!--<div class="more-news-a" style="margin-top:6px;margin-bottom:6px;"><%= "#{@user.first_name} #{@user.last_name}" %></div>-->
	<div style="">Your profile is 21% complete</div>
	<div class="progress progress-striped active">
	  <div class="bar" style="width: 21%;"></div>
	</div>		
	<div style="clear:both;"></div>        
      </div>
    </div>      
    <div class="margin_bottom_20"></div>
  </div>
  <div class="contact">
    <div class="header_02"><span style="color: #137DC0;">My Calendar</span></div>
    <!-- http://www.webvanta.com/post/118104-fullcalendar-an-excellent-jquery-calendar-plug-in -->
    <div class="news_image" style="width: 306px;"><a href="#"><img src="http://www.webvanta.com/rendition.site-thumb/blog/fullcalendar.png" alt="image 3" width="310px" height="200px"></a></div>    
  </div>
  <div style="clear:both;"></div>
<div class="header_02" style="margin-top: 6px;"><span style="color: #137DC0;">Tips to improve my product</span></div>  
  <div class="indent-left2 img-indent-bot">    
    <ul class="list-1" style="list-style: none;">
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
      <li><a href="#"><span class="color-2">Voluptas assumenda</span> est, omnis dolor repellendus.</a></li>
      <li class="last-item"><a href="#"><span class="color-2">Temporibus autem</span> quibusdam officiis debitis aut rerum necessit.</a></li>
      <li><a href="#"><span class="color-2">Praesentum voluptatum</span> deleniti atque corrupti quos dolores.</a></li>
      <li><a href="#"><span class="color-2">Culpa officia deserunt</span> mollitia animi id est laborum.</a></li>
    </ul>
  </div>
</div>


<style type="text/css">

.button_example{
border:1px solid #2F6E3A; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;width:80px;font-family:arial, helvetica, sans-serif; padding: 5px 5px 5px 5px; text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #a9db80;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9db80), color-stop(100%, #96c56f));
 background-image: -webkit-linear-gradient(top, #a9db80, #96c56f);
 background-image: -moz-linear-gradient(top, #a9db80, #96c56f);
 background-image: -ms-linear-gradient(top, #a9db80, #96c56f);
 background-image: -o-linear-gradient(top, #a9db80, #96c56f);
 background-image: linear-gradient(top, #a9db80, #96c56f);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#a9db80, endColorstr=#96c56f);
}

.button_example:hover{
 border:1px solid #74bf36; background-color: #8ed058;
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#8ed058), color-stop(100%, #7bb64b));
 background-image: -webkit-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -moz-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -ms-linear-gradient(top, #8ed058, #7bb64b);
 background-image: -o-linear-gradient(top, #8ed058, #7bb64b);
 background-image: linear-gradient(top, #8ed058, #7bb64b);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#8ed058, endColorstr=#7bb64b);
}


.img-indent-bot {
margin-bottom: 25px;
}

.list-1 li {
font-family: Georgia;
font-size: 100%;
line-height: 25px;
padding: 0 0 15px 41px;
background: url(/images/marker-1.png) 0 2px no-repeat;
}

.list-1 li a{color: #F78F07;}
.list-1 li a:hover{color: #E77E02;}
.list-1 li a:hover span{color: #E77E02;}
.list-1 li a {
display: inline-block;
color: #818280;
cursor: pointer;
text-decoration: none;
}


.color-2 {
font-size: 17px;
color: black;
}
</style>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>